title: Angelo Ceccato Blog
homepageName: ANGELO CECCATO
logo: /img/avatar_logo.webp
description: or AngeloChecked
domain: angeloceccato.it

social: 
  - name: Twitter
    link: https://twitter.com/angelochecked
  - name: Mastodon
    link: https://mastodon.social/@angelochecked
  - name: Linkedin
    link: https://www.linkedin.com/in/angeloceccato/
  - name: Github
    link: https://github.com/AngeloChecked
  - name: Mail
    link: mailto:angelochecked@gmail.com
            
            
            
            
            
